### PR TITLE
Fix error when hexes of length 64 are used as signer secrets

### LINKED ISSUE #27: Signer provided with hex value of 64 charaters throws _wrapInput error
When providing a secret value hex to `BlsSignerFactory.getSigner` that has a length of 66 (0x + 64), an error is thrown from `mcl-wasm`:

```sh
     Error: err _wrapInput 0xdbe576b4818846aa77e82f4ed5fa78f92766b141f282d36703886d196df39322
      at /home/jacque006/workspaces/hubble/hubble-bls/node_modules/mcl-wasm/dist/mcl.js:128:23
      at Fr._setter (node_modules/mcl-wasm/dist/value-types.js:57:19)
      at Fr.setStr (node_modules/mcl-wasm/dist/value-types.js:127:14)
      at parseFr (src/mcl.ts:212:8)
      at BlsSignerFactory.getSecret (src/signer.ts:95:27)
      at BlsSignerFactory.getSigner (src/signer.ts:85:29)
      at Context.<anonymous> (test/signer.test.ts:70:32)
```
Signer: https://github.com/thehubbleproject/hubble-bls/blob/master/src/signer.ts#L87
mcl: https://github.com/thehubbleproject/hubble-bls/blob/master/src/mcl.ts#L213-L218

This appears to be due to the `mcl-wasm` update to `v1.0.0`;

### PR DESCRIPTION
**Pull request by jacque006**
Change behavior of signer secret parsing to do a direct Fr string set, with a fallback of hashing the secret input on error.
Add validateHex function.
Add wider range of secret values to signer tests.
Use mcl-wasm Typescript types instead of any.

Resolves https://github.com/thehubbleproject/hubble-bls/issues/27

### CODE REVIEW

File: src/signer.ts [hunk 1]
```diff
@@ -82,11 +82,7 @@ export class BlsSignerFactory {
     private constructor() {}
 
     public getSigner(domain: Domain, secretHex?: string) {
-        const secret = secretHex
-            ? secretHex.length == 66
-                ? parseFr(secretHex)
```
Comment (jacque006) [inline src/signer.ts:87]: After the `mcl-wasm@1.0.0` update, `parseFr` no longer works with hexes of length 64 (string length 66). It does work on hex values of length 1 (i.e. `0x1`) up to length 63, one less than what `keccak256` produces.

@ChihChengLiang Do you know why this might have changed between `mcl-wasm` versions, and if there are any implications to switching to just use `setHashFr`?

File: test/signer.test.ts [hunk 2]
```diff
@@ -60,4 +60,24 @@ describe("BLS Signer", async () => {
...
     }).timeout(20000);
+
+    describe("getSigner", () => {
+        let factory: BlsSignerFactory;
+        before(async () => {
+            factory = await BlsSignerFactory.new();
+        });
+
+        [
+            "",
```
Comment (jacque006) [inline test/signer.test.ts:71]: This parses in to `mcl` correctly, so I assume it is a valid secret. However, this could be passed in if a developer/user makes a mistake. Do we want to throw if the secret passed in is empty?

File: src/signer.ts (hunk 1 above)
Comment (ChihChengLiang) [reply src/signer.ts:87]: I don't know the changes in `mcl-wasm`. Maybe #22 is related?

File: test/signer.test.ts (hunk 2 above)
Comment (jacque006) [reply test/signer.test.ts:83]: 0 is a valid value for a secret so leave as is for now.

File: src/signer.ts (hunk 1 above)
Comment (jacque006) [reply src/signer.ts:87]: I was unable to determine a way to validate that the hex is in range. So I ended up setting up the secret parsing for the signer as such:
- If the secret is missing/empty, generate a random one.
- Attempt to directly set the hex value. If this fails, fall back to hashing the secret.

I think this should cover the range of use cases and expected outputs.

**Comment by jacque006** [comment]
@ChihChengLiang Ready for your final review.

File: src/signer.ts (hunk 1 above)
Comment (ChihChengLiang) [reply src/signer.ts:87]: Looks like a good solution. @philsippl Would you like to provide a test case example value to make sure this change doesn't break your use case?

**Review by ChihChengLiang — APPROVED** [review]
LGTM on my side.

**Comment by jacque006** [comment]
Going to merge and release this as is.

@philsippl if this breaks your use case we can fix in follow up work.

**Comment by philsippl** [comment]
> Going to merge and release this as is.
> 
> @philsippl if this breaks your use case we can fix in follow up work.

@jacque006 @ChihChengLiang not sure if you saw my comment from a few weeks back, so posting here again in the thread 👇 

> @ChihChengLiang @jacque006 Sorry for my late reponse, I've been off for a bit and missed the notification. The proposed changes are fine for my use-case (because the default case is to call parseFr). However, I think the approach with try/catch leads to very unintentional behavior (my originally proposed implementation also suffers from this issue).
The error that @jacque006 filed actually only appears on some hashes, specifically those that converted back to bigint don't fit in the prime field (parseFr assumes a field element).
So if we go with the try/catch, we will call parseFr on some hashes and setHashFr on the rest. I don't think this is desired and might create weird compatibility issues with other libraries.
IMO instead of treating this implicitly like @jacque006 and I tried, we should just make it explicit what happens and introduce two distinct getSigner methods, one for passing a Fr directly, and another one that just accepts an arbitrary seed that then calls setHashFr. What do you guys think?

**Comment by jacque006** [comment]
@philsippl Agreed, I like the split approach. Created https://github.com/thehubbleproject/hubble-bls/issues/30 to address.
